# Generated by Django 5.1.4 on 2025-01-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
